### ISSUE TITLE
Support more than one passdb entry

### ISSUE THREAD

**Issue by loxley** [onddo/dovecot-cookbook#14]
I wonder if it would be possible to make some support for having multiple passdb/userdb entries as that is allowed by Dovecot.

It's useful for situations where you depend on more than one way of authenticating users.

Example I have a static conf a'la:

       "auth": {
         "static": {
           "passdb": [
             {
               "driver": "static",
               "args": [
                 "password=123456789"
               ],
               "master": "yes"
             }
           ]
         },

But I also would like to have:

"dict": {
           "passdb": [
             {
               "driver": "dict",
               "args": "/etc/dovecot/dovecot-dict-auth.conf.ext"
             }
           ],
           "userdb": [
             {
               "driver": "dict",
               "args": "/etc/dovecot/dovecot-dict-auth.conf.ext"
             }
           ]
         }

Right now it seems that the cookbook never parses this second passdb entry or it gets overwritten by the one in the static section.

Do you think this is fixable ?

**Comment by loxley** [comment]
And i was stupid, it seems to work :)

**Comment by zuazo** [comment]
OK. It had seemed strange to me at first :smile:

**Comment by loxley** [comment]
I was suffering from the leapsecond :)
