### ISSUE TITLE
Protect sensitive information from read

### ISSUE THREAD

**Issue by claudex** [onddo/dovecot-cookbook#4]
There is only one attribute to set the mode for the configuration files but there is two kinds of file. Most of them should be world readable (to have tools like `doveadm pw` or `/usr/lib/dovecot/deliver` working) but those with sensitive information like `dovecot-sql.conf.ext` and `dovecot-dict-sql.conf.ext` should not be world readable.

**Comment by iiro** [comment]
Hi,

and first of all - excellent work! :)

Did you get this setting to play nice with PostfixAdmin too? PFA needs to read some of these files if I remember correctly...

I would definitely love to use file mode 640 for stuff - but then PFA stops working (it's running on it's own username).

**Comment by zuazo** [comment]
Sorry, @iiro, I have not tried it. But I'll let you know if I ever get it to work.
